// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czqeptowzskqhclplscl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cWVwdG93enNrcWhjbHBsc2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MTQ0NzcsImV4cCI6MjA1MzM5MDQ3N30.zhaNBjFaI0gNyqwbnlprhWnWDcff38I9OVq1boOKmlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);